# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Person.ui'
#
# Created: Mon Jan 30 21:45:22 2012
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Person(object):
    def setupUi(self, Person):
        Person.setObjectName(_fromUtf8("Person"))
        Person.resize(730, 550)
        Person.setWindowTitle(QtGui.QApplication.translate("Person", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.verticalLayout = QtGui.QVBoxLayout(Person)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox = QtGui.QGroupBox(Person)
        self.groupBox.setTitle(QtGui.QApplication.translate("Person", "Basics", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.formLayout = QtGui.QFormLayout(self.groupBox)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setText(QtGui.QApplication.translate("Person", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_3)
        self.nameLineEdit = QtGui.QLineEdit(self.groupBox)
        self.nameLineEdit.setObjectName(_fromUtf8("nameLineEdit"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.nameLineEdit)
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setText(QtGui.QApplication.translate("Person", "Type", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_5)
        self.typeLineEdit = QtGui.QLineEdit(self.groupBox)
        self.typeLineEdit.setReadOnly(True)
        self.typeLineEdit.setObjectName(_fromUtf8("typeLineEdit"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.typeLineEdit)
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setText(QtGui.QApplication.translate("Person", "Level", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_6)
        self.levelLineEdit = QtGui.QLineEdit(self.groupBox)
        self.levelLineEdit.setReadOnly(True)
        self.levelLineEdit.setObjectName(_fromUtf8("levelLineEdit"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.levelLineEdit)
        self.label_12 = QtGui.QLabel(self.groupBox)
        self.label_12.setText(QtGui.QApplication.translate("Person", "Experience", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_12)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.expComboBox = QtGui.QComboBox(self.groupBox)
        self.expComboBox.setObjectName(_fromUtf8("expComboBox"))
        self.horizontalLayout_2.addWidget(self.expComboBox)
        self.expLineEdit = QtGui.QLineEdit(self.groupBox)
        self.expLineEdit.setReadOnly(True)
        self.expLineEdit.setObjectName(_fromUtf8("expLineEdit"))
        self.horizontalLayout_2.addWidget(self.expLineEdit)
        self.formLayout.setLayout(6, QtGui.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.label_11 = QtGui.QLabel(self.groupBox)
        self.label_11.setText(QtGui.QApplication.translate("Person", "Employer", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_11)
        self.employerLineEdit = QtGui.QLineEdit(self.groupBox)
        self.employerLineEdit.setReadOnly(True)
        self.employerLineEdit.setObjectName(_fromUtf8("employerLineEdit"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.employerLineEdit)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(Person)
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Person", "Finances", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.formLayout_2 = QtGui.QFormLayout(self.groupBox_2)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_13 = QtGui.QLabel(self.groupBox_2)
        self.label_13.setText(QtGui.QApplication.translate("Person", "Net Worth", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_13)
        self.netWorthLineEdit = QtGui.QLineEdit(self.groupBox_2)
        self.netWorthLineEdit.setReadOnly(True)
        self.netWorthLineEdit.setObjectName(_fromUtf8("netWorthLineEdit"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.netWorthLineEdit)
        self.label = QtGui.QLabel(self.groupBox_2)
        self.label.setText(QtGui.QApplication.translate("Person", "Salary", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label)
        self.salaryLineEdit = QtGui.QLineEdit(self.groupBox_2)
        self.salaryLineEdit.setReadOnly(True)
        self.salaryLineEdit.setObjectName(_fromUtf8("salaryLineEdit"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.salaryLineEdit)
        self.label_2 = QtGui.QLabel(self.groupBox_2)
        self.label_2.setText(QtGui.QApplication.translate("Person", "Other Income", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_2)
        self.otherIncomeLineEdit = QtGui.QLineEdit(self.groupBox_2)
        self.otherIncomeLineEdit.setReadOnly(True)
        self.otherIncomeLineEdit.setObjectName(_fromUtf8("otherIncomeLineEdit"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.otherIncomeLineEdit)
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setText(QtGui.QApplication.translate("Person", "Total Income", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_4)
        self.totalIncomeLineEdit = QtGui.QLineEdit(self.groupBox_2)
        self.totalIncomeLineEdit.setReadOnly(True)
        self.totalIncomeLineEdit.setObjectName(_fromUtf8("totalIncomeLineEdit"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.totalIncomeLineEdit)
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        self.label_7.setText(QtGui.QApplication.translate("Person", "Taxes", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_7)
        self.taxesLineEdit = QtGui.QLineEdit(self.groupBox_2)
        self.taxesLineEdit.setReadOnly(True)
        self.taxesLineEdit.setObjectName(_fromUtf8("taxesLineEdit"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.FieldRole, self.taxesLineEdit)
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        self.label_8.setText(QtGui.QApplication.translate("Person", "Supplies", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_8)
        self.supplyLineEdit = QtGui.QLineEdit(self.groupBox_2)
        self.supplyLineEdit.setReadOnly(True)
        self.supplyLineEdit.setObjectName(_fromUtf8("supplyLineEdit"))
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.FieldRole, self.supplyLineEdit)
        self.label_9 = QtGui.QLabel(self.groupBox_2)
        self.label_9.setText(QtGui.QApplication.translate("Person", "Other Expenses", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout_2.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_9)
        self.otherExpensesLineEdit = QtGui.QLineEdit(self.groupBox_2)
        self.otherExpensesLineEdit.setReadOnly(True)
        self.otherExpensesLineEdit.setObjectName(_fromUtf8("otherExpensesLineEdit"))
        self.formLayout_2.setWidget(6, QtGui.QFormLayout.FieldRole, self.otherExpensesLineEdit)
        self.label_10 = QtGui.QLabel(self.groupBox_2)
        self.label_10.setText(QtGui.QApplication.translate("Person", "Net", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.formLayout_2.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_10)
        self.netLineEdit = QtGui.QLineEdit(self.groupBox_2)
        self.netLineEdit.setReadOnly(True)
        self.netLineEdit.setObjectName(_fromUtf8("netLineEdit"))
        self.formLayout_2.setWidget(7, QtGui.QFormLayout.FieldRole, self.netLineEdit)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtGui.QGroupBox(Person)
        self.groupBox_3.setTitle(QtGui.QApplication.translate("Person", "Actions", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.findShelterPushButton = QtGui.QPushButton(self.groupBox_3)
        self.findShelterPushButton.setText(QtGui.QApplication.translate("Person", "Find Shelter", None, QtGui.QApplication.UnicodeUTF8))
        self.findShelterPushButton.setObjectName(_fromUtf8("findShelterPushButton"))
        self.gridLayout.addWidget(self.findShelterPushButton, 3, 1, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.upgradeComboBox = QtGui.QComboBox(self.groupBox_3)
        self.upgradeComboBox.setObjectName(_fromUtf8("upgradeComboBox"))
        self.horizontalLayout_3.addWidget(self.upgradeComboBox)
        self.upgradePushButton = QtGui.QPushButton(self.groupBox_3)
        self.upgradePushButton.setText(QtGui.QApplication.translate("Person", "Upgrade", None, QtGui.QApplication.UnicodeUTF8))
        self.upgradePushButton.setObjectName(_fromUtf8("upgradePushButton"))
        self.horizontalLayout_3.addWidget(self.upgradePushButton)
        self.gridLayout.addLayout(self.horizontalLayout_3, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_3)

        self.retranslateUi(Person)
        QtCore.QMetaObject.connectSlotsByName(Person)

    def retranslateUi(self, Person):
        pass

