# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ManitaeMainWindow.ui'
#
# Created: Wed Mar  7 03:27:06 2012
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_ManitaeMainWindow(object):
    def setupUi(self, ManitaeMainWindow):
        ManitaeMainWindow.setObjectName(_fromUtf8("ManitaeMainWindow"))
        ManitaeMainWindow.resize(1305, 666)
        ManitaeMainWindow.setWindowTitle(QtGui.QApplication.translate("ManitaeMainWindow", "Manitae", None, QtGui.QApplication.UnicodeUTF8))
        self.centralWidget = QtGui.QWidget(ManitaeMainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralWidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.tabWidget = QtGui.QTabWidget(self.centralWidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout = QtGui.QGridLayout(self.tab)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.widget = ManitaeSummary(self.tab)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.peopleTabWidget = QtGui.QTabWidget(self.tab_2)
        self.peopleTabWidget.setObjectName(_fromUtf8("peopleTabWidget"))
        self.gridLayout_3.addWidget(self.peopleTabWidget, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.gridLayout_7 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.mapTabWidget = QtGui.QWidget(self.tab_3)
        self.mapTabWidget.setObjectName(_fromUtf8("mapTabWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.mapTabWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.mapView = QtDeclarative.QDeclarativeView(self.mapTabWidget)
        self.mapView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.mapView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.mapView.setResizeMode(QtDeclarative.QDeclarativeView.SizeViewToRootObject)
        self.mapView.setObjectName(_fromUtf8("mapView"))
        self.verticalLayout.addWidget(self.mapView)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupBox = QtGui.QGroupBox(self.mapTabWidget)
        self.groupBox.setTitle(QtGui.QApplication.translate("ManitaeMainWindow", "On This Square", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.formLayout_2 = QtGui.QFormLayout(self.groupBox)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setText(QtGui.QApplication.translate("ManitaeMainWindow", "Position", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.positionLineEdit = QtGui.QLineEdit(self.groupBox)
        self.positionLineEdit.setReadOnly(True)
        self.positionLineEdit.setObjectName(_fromUtf8("positionLineEdit"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.positionLineEdit)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setText(QtGui.QApplication.translate("ManitaeMainWindow", "Object", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.tileOccupantLineEdit = QtGui.QLineEdit(self.groupBox)
        self.tileOccupantLineEdit.setReadOnly(True)
        self.tileOccupantLineEdit.setObjectName(_fromUtf8("tileOccupantLineEdit"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.tileOccupantLineEdit)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.mapTabWidget)
        self.groupBox_2.setTitle(QtGui.QApplication.translate("ManitaeMainWindow", "Actions", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.buildPushButton = QtGui.QPushButton(self.groupBox_2)
        self.buildPushButton.setEnabled(False)
        self.buildPushButton.setText(QtGui.QApplication.translate("ManitaeMainWindow", "Build", None, QtGui.QApplication.UnicodeUTF8))
        self.buildPushButton.setObjectName(_fromUtf8("buildPushButton"))
        self.gridLayout_6.addWidget(self.buildPushButton, 0, 1, 1, 1)
        self.buildComboBox = QtGui.QComboBox(self.groupBox_2)
        self.buildComboBox.setObjectName(_fromUtf8("buildComboBox"))
        self.gridLayout_6.addWidget(self.buildComboBox, 0, 0, 1, 1)
        self.pushButton_2 = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_2.setEnabled(False)
        self.pushButton_2.setText(QtGui.QApplication.translate("ManitaeMainWindow", "Destroy", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.gridLayout_6.addWidget(self.pushButton_2, 1, 1, 1, 1)
        self.goToTabPushButton = QtGui.QPushButton(self.groupBox_2)
        self.goToTabPushButton.setEnabled(False)
        self.goToTabPushButton.setText(QtGui.QApplication.translate("ManitaeMainWindow", "Go to Unit\'s tab", None, QtGui.QApplication.UnicodeUTF8))
        self.goToTabPushButton.setObjectName(_fromUtf8("goToTabPushButton"))
        self.gridLayout_6.addWidget(self.goToTabPushButton, 1, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.gridLayout_7.addWidget(self.mapTabWidget, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)
        ManitaeMainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(ManitaeMainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1305, 21))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuGame = QtGui.QMenu(self.menuBar)
        self.menuGame.setTitle(QtGui.QApplication.translate("ManitaeMainWindow", "Game", None, QtGui.QApplication.UnicodeUTF8))
        self.menuGame.setObjectName(_fromUtf8("menuGame"))
        self.menuStats = QtGui.QMenu(self.menuBar)
        self.menuStats.setTitle(QtGui.QApplication.translate("ManitaeMainWindow", "Stats", None, QtGui.QApplication.UnicodeUTF8))
        self.menuStats.setObjectName(_fromUtf8("menuStats"))
        self.menuHelp = QtGui.QMenu(self.menuBar)
        self.menuHelp.setTitle(QtGui.QApplication.translate("ManitaeMainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        ManitaeMainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtGui.QToolBar(ManitaeMainWindow)
        self.mainToolBar.setMovable(False)
        self.mainToolBar.setFloatable(False)
        self.mainToolBar.setObjectName(_fromUtf8("mainToolBar"))
        ManitaeMainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(ManitaeMainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        ManitaeMainWindow.setStatusBar(self.statusBar)
        self.dockWidget = QtGui.QDockWidget(ManitaeMainWindow)
        self.dockWidget.setWindowTitle(QtGui.QApplication.translate("ManitaeMainWindow", "Notices", None, QtGui.QApplication.UnicodeUTF8))
        self.dockWidget.setObjectName(_fromUtf8("dockWidget"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.gridLayout_4 = QtGui.QGridLayout(self.dockWidgetContents)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.noticeLog = QtGui.QTextEdit(self.dockWidgetContents)
        self.noticeLog.setEnabled(True)
        self.noticeLog.setReadOnly(True)
        self.noticeLog.setHtml(QtGui.QApplication.translate("ManitaeMainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">This is a notice.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#c00000;\">This is a warning!</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Messages will appear below.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Click on &quot;File&gt;New Game&quot; or press Ctrl+N to start.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.noticeLog.setObjectName(_fromUtf8("noticeLog"))
        self.gridLayout_4.addWidget(self.noticeLog, 0, 0, 1, 1)
        self.dockWidget.setWidget(self.dockWidgetContents)
        ManitaeMainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget)
        self.actionNew_Game = QtGui.QAction(ManitaeMainWindow)
        self.actionNew_Game.setText(QtGui.QApplication.translate("ManitaeMainWindow", "New Game", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew_Game.setShortcut(QtGui.QApplication.translate("ManitaeMainWindow", "Ctrl+N", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew_Game.setObjectName(_fromUtf8("actionNew_Game"))
        self.actionEnd_Turn = QtGui.QAction(ManitaeMainWindow)
        self.actionEnd_Turn.setText(QtGui.QApplication.translate("ManitaeMainWindow", "End Turn", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEnd_Turn.setShortcut(QtGui.QApplication.translate("ManitaeMainWindow", "Ctrl+T", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEnd_Turn.setObjectName(_fromUtf8("actionEnd_Turn"))
        self.actionExit = QtGui.QAction(ManitaeMainWindow)
        self.actionExit.setText(QtGui.QApplication.translate("ManitaeMainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setShortcut(QtGui.QApplication.translate("ManitaeMainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setMenuRole(QtGui.QAction.QuitRole)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionPopulation = QtGui.QAction(ManitaeMainWindow)
        self.actionPopulation.setText(QtGui.QApplication.translate("ManitaeMainWindow", "Population", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPopulation.setShortcut(QtGui.QApplication.translate("ManitaeMainWindow", "Ctrl+P", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPopulation.setObjectName(_fromUtf8("actionPopulation"))
        self.actionEconomy = QtGui.QAction(ManitaeMainWindow)
        self.actionEconomy.setText(QtGui.QApplication.translate("ManitaeMainWindow", "Economy", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEconomy.setShortcut(QtGui.QApplication.translate("ManitaeMainWindow", "Ctrl+E", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEconomy.setObjectName(_fromUtf8("actionEconomy"))
        self.actionResources = QtGui.QAction(ManitaeMainWindow)
        self.actionResources.setText(QtGui.QApplication.translate("ManitaeMainWindow", "Resources", None, QtGui.QApplication.UnicodeUTF8))
        self.actionResources.setShortcut(QtGui.QApplication.translate("ManitaeMainWindow", "Ctrl+Shift+R", None, QtGui.QApplication.UnicodeUTF8))
        self.actionResources.setObjectName(_fromUtf8("actionResources"))
        self.actionResearch = QtGui.QAction(ManitaeMainWindow)
        self.actionResearch.setText(QtGui.QApplication.translate("ManitaeMainWindow", "Research", None, QtGui.QApplication.UnicodeUTF8))
        self.actionResearch.setShortcut(QtGui.QApplication.translate("ManitaeMainWindow", "Ctrl+R", None, QtGui.QApplication.UnicodeUTF8))
        self.actionResearch.setObjectName(_fromUtf8("actionResearch"))
        self.actionHelp = QtGui.QAction(ManitaeMainWindow)
        self.actionHelp.setText(QtGui.QApplication.translate("ManitaeMainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHelp.setShortcut(QtGui.QApplication.translate("ManitaeMainWindow", "F1", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHelp.setObjectName(_fromUtf8("actionHelp"))
        self.menuGame.addAction(self.actionNew_Game)
        self.menuGame.addSeparator()
        self.menuGame.addAction(self.actionEnd_Turn)
        self.menuGame.addSeparator()
        self.menuGame.addAction(self.actionExit)
        self.menuStats.addAction(self.actionPopulation)
        self.menuStats.addAction(self.actionEconomy)
        self.menuStats.addAction(self.actionResearch)
        self.menuStats.addAction(self.actionResources)
        self.menuHelp.addAction(self.actionHelp)
        self.menuBar.addAction(self.menuGame.menuAction())
        self.menuBar.addAction(self.menuStats.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(ManitaeMainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL(_fromUtf8("triggered()")), ManitaeMainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(ManitaeMainWindow)

    def retranslateUi(self, ManitaeMainWindow):
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("ManitaeMainWindow", "Summary", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("ManitaeMainWindow", "Population", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("ManitaeMainWindow", "Map", None, QtGui.QApplication.UnicodeUTF8))

from PyQt4 import QtDeclarative
from ManitaeSummary import ManitaeSummary
