# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Hunter.ui'
#
# Created: Fri Jan 27 20:03:27 2012
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Hunter(object):
    def setupUi(self, Hunter):
        Hunter.setObjectName(_fromUtf8("Hunter"))
        Hunter.resize(756, 534)
        Hunter.setWindowTitle(QtGui.QApplication.translate("Hunter", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.verticalLayout = QtGui.QVBoxLayout(Hunter)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.basicsGroupBox = QtGui.QGroupBox(Hunter)
        self.basicsGroupBox.setTitle(QtGui.QApplication.translate("Hunter", "Basics", None, QtGui.QApplication.UnicodeUTF8))
        self.basicsGroupBox.setObjectName(_fromUtf8("basicsGroupBox"))
        self.formLayout = QtGui.QFormLayout(self.basicsGroupBox)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtGui.QLabel(self.basicsGroupBox)
        self.label.setText(QtGui.QApplication.translate("Hunter", "Production level", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.prodLevelLineEdit = QtGui.QLineEdit(self.basicsGroupBox)
        self.prodLevelLineEdit.setReadOnly(True)
        self.prodLevelLineEdit.setObjectName(_fromUtf8("prodLevelLineEdit"))
        self.horizontalLayout_2.addWidget(self.prodLevelLineEdit)
        self.label_3 = QtGui.QLabel(self.basicsGroupBox)
        self.label_3.setText(QtGui.QApplication.translate("Hunter", " /turn", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_2.addWidget(self.label_3)
        self.formLayout.setLayout(1, QtGui.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.label_2 = QtGui.QLabel(self.basicsGroupBox)
        self.label_2.setText(QtGui.QApplication.translate("Hunter", "Employees", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_2)
        self.employeeLineEdit = QtGui.QLineEdit(self.basicsGroupBox)
        self.employeeLineEdit.setReadOnly(True)
        self.employeeLineEdit.setObjectName(_fromUtf8("employeeLineEdit"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.employeeLineEdit)
        self.label_4 = QtGui.QLabel(self.basicsGroupBox)
        self.label_4.setText(QtGui.QApplication.translate("Hunter", "Production On", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_4)
        self.prodOnCheckBox = QtGui.QCheckBox(self.basicsGroupBox)
        self.prodOnCheckBox.setText(_fromUtf8(""))
        self.prodOnCheckBox.setObjectName(_fromUtf8("prodOnCheckBox"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.prodOnCheckBox)
        self.label_5 = QtGui.QLabel(self.basicsGroupBox)
        self.label_5.setText(QtGui.QApplication.translate("Hunter", "Salary", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_5)
        self.salaryLineEdit = QtGui.QLineEdit(self.basicsGroupBox)
        self.salaryLineEdit.setReadOnly(True)
        self.salaryLineEdit.setObjectName(_fromUtf8("salaryLineEdit"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.salaryLineEdit)
        self.label_6 = QtGui.QLabel(self.basicsGroupBox)
        self.label_6.setText(QtGui.QApplication.translate("Hunter", "Level", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_6)
        self.label_7 = QtGui.QLabel(self.basicsGroupBox)
        self.label_7.setText(QtGui.QApplication.translate("Hunter", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.label_7)
        self.verticalLayout.addWidget(self.basicsGroupBox)
        self.employeesGroupBox = QtGui.QGroupBox(Hunter)
        self.employeesGroupBox.setTitle(QtGui.QApplication.translate("Hunter", "Employees", None, QtGui.QApplication.UnicodeUTF8))
        self.employeesGroupBox.setObjectName(_fromUtf8("employeesGroupBox"))
        self.gridLayout_4 = QtGui.QGridLayout(self.employeesGroupBox)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.employeeListView = QtGui.QListView(self.employeesGroupBox)
        self.employeeListView.setObjectName(_fromUtf8("employeeListView"))
        self.gridLayout_4.addWidget(self.employeeListView, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.employeesGroupBox)
        self.actionsGroupBox = QtGui.QGroupBox(Hunter)
        self.actionsGroupBox.setTitle(QtGui.QApplication.translate("Hunter", "Actions", None, QtGui.QApplication.UnicodeUTF8))
        self.actionsGroupBox.setObjectName(_fromUtf8("actionsGroupBox"))
        self.gridLayout = QtGui.QGridLayout(self.actionsGroupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.upgradeButton = QtGui.QPushButton(self.actionsGroupBox)
        self.upgradeButton.setText(QtGui.QApplication.translate("Hunter", "Upgrade", None, QtGui.QApplication.UnicodeUTF8))
        self.upgradeButton.setObjectName(_fromUtf8("upgradeButton"))
        self.gridLayout_2.addWidget(self.upgradeButton, 0, 0, 1, 1)
        self.destroyButton = QtGui.QPushButton(self.actionsGroupBox)
        self.destroyButton.setText(QtGui.QApplication.translate("Hunter", "Destroy", None, QtGui.QApplication.UnicodeUTF8))
        self.destroyButton.setObjectName(_fromUtf8("destroyButton"))
        self.gridLayout_2.addWidget(self.destroyButton, 0, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 2, 1, 1, 1)
        self.hireButton = QtGui.QPushButton(self.actionsGroupBox)
        self.hireButton.setText(QtGui.QApplication.translate("Hunter", "Hire", None, QtGui.QApplication.UnicodeUTF8))
        self.hireButton.setObjectName(_fromUtf8("hireButton"))
        self.gridLayout.addWidget(self.hireButton, 0, 1, 1, 1)
        self.hireComboBox = QtGui.QComboBox(self.actionsGroupBox)
        self.hireComboBox.setObjectName(_fromUtf8("hireComboBox"))
        self.gridLayout.addWidget(self.hireComboBox, 0, 0, 1, 1)
        self.fireComboBox = QtGui.QComboBox(self.actionsGroupBox)
        self.fireComboBox.setObjectName(_fromUtf8("fireComboBox"))
        self.gridLayout.addWidget(self.fireComboBox, 1, 0, 1, 1)
        self.fireButton = QtGui.QPushButton(self.actionsGroupBox)
        self.fireButton.setText(QtGui.QApplication.translate("Hunter", "Fire", None, QtGui.QApplication.UnicodeUTF8))
        self.fireButton.setObjectName(_fromUtf8("fireButton"))
        self.gridLayout.addWidget(self.fireButton, 1, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 0, 1, 1)
        self.verticalLayout.addWidget(self.actionsGroupBox)

        self.retranslateUi(Hunter)
        QtCore.QMetaObject.connectSlotsByName(Hunter)

    def retranslateUi(self, Hunter):
        pass

