# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ManitaeSummary.ui'
#
# Created: Fri Mar  2 07:54:29 2012
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_ManitaeSummary(object):
    def setupUi(self, ManitaeSummary):
        ManitaeSummary.setObjectName(_fromUtf8("ManitaeSummary"))
        ManitaeSummary.resize(929, 599)
        ManitaeSummary.setWindowTitle(QtGui.QApplication.translate("ManitaeSummary", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.gridLayout_2 = QtGui.QGridLayout(ManitaeSummary)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.groupBox = QtGui.QGroupBox(ManitaeSummary)
        self.groupBox.setTitle(QtGui.QApplication.translate("ManitaeSummary", "Population", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.formLayout_2 = QtGui.QFormLayout(self.groupBox)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setText(QtGui.QApplication.translate("ManitaeSummary", "Total Population", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.totalPopulation = QtGui.QLineEdit(self.groupBox)
        self.totalPopulation.setEnabled(True)
        self.totalPopulation.setText(QtGui.QApplication.translate("ManitaeSummary", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.totalPopulation.setReadOnly(True)
        self.totalPopulation.setObjectName(_fromUtf8("totalPopulation"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.totalPopulation)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setText(QtGui.QApplication.translate("ManitaeSummary", "Working Population", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.workingPopulation = QtGui.QLineEdit(self.groupBox)
        self.workingPopulation.setEnabled(True)
        self.workingPopulation.setText(QtGui.QApplication.translate("ManitaeSummary", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.workingPopulation.setReadOnly(True)
        self.workingPopulation.setObjectName(_fromUtf8("workingPopulation"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.workingPopulation)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setText(QtGui.QApplication.translate("ManitaeSummary", "Taxed Population", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_3)
        self.taxedPopulation = QtGui.QLineEdit(self.groupBox)
        self.taxedPopulation.setEnabled(True)
        self.taxedPopulation.setText(QtGui.QApplication.translate("ManitaeSummary", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.taxedPopulation.setReadOnly(True)
        self.taxedPopulation.setObjectName(_fromUtf8("taxedPopulation"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.taxedPopulation)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(ManitaeSummary)
        self.groupBox_2.setTitle(QtGui.QApplication.translate("ManitaeSummary", "Economy", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.formLayout = QtGui.QFormLayout(self.groupBox_2)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setText(QtGui.QApplication.translate("ManitaeSummary", "Total Money", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_5)
        self.totalMoney = QtGui.QLineEdit(self.groupBox_2)
        self.totalMoney.setEnabled(True)
        self.totalMoney.setText(QtGui.QApplication.translate("ManitaeSummary", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.totalMoney.setReadOnly(True)
        self.totalMoney.setObjectName(_fromUtf8("totalMoney"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.totalMoney)
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setText(QtGui.QApplication.translate("ManitaeSummary", "Tax Revenue", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_6)
        self.taxRevenue = QtGui.QLineEdit(self.groupBox_2)
        self.taxRevenue.setEnabled(True)
        self.taxRevenue.setText(QtGui.QApplication.translate("ManitaeSummary", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.taxRevenue.setReadOnly(True)
        self.taxRevenue.setObjectName(_fromUtf8("taxRevenue"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.taxRevenue)
        self.label_11 = QtGui.QLabel(self.groupBox_2)
        self.label_11.setText(QtGui.QApplication.translate("ManitaeSummary", "Other Revenue", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_11)
        self.otherRevenue = QtGui.QLineEdit(self.groupBox_2)
        self.otherRevenue.setEnabled(True)
        self.otherRevenue.setText(QtGui.QApplication.translate("ManitaeSummary", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.otherRevenue.setReadOnly(True)
        self.otherRevenue.setObjectName(_fromUtf8("otherRevenue"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.otherRevenue)
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        self.label_7.setText(QtGui.QApplication.translate("ManitaeSummary", "Workers\' Salary", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_7)
        self.workersSalary = QtGui.QLineEdit(self.groupBox_2)
        self.workersSalary.setEnabled(True)
        self.workersSalary.setText(QtGui.QApplication.translate("ManitaeSummary", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.workersSalary.setReadOnly(True)
        self.workersSalary.setObjectName(_fromUtf8("workersSalary"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.workersSalary)
        self.label_9 = QtGui.QLabel(self.groupBox_2)
        self.label_9.setText(QtGui.QApplication.translate("ManitaeSummary", "Construction Costs", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_9)
        self.constructionCosts = QtGui.QLineEdit(self.groupBox_2)
        self.constructionCosts.setEnabled(True)
        self.constructionCosts.setText(QtGui.QApplication.translate("ManitaeSummary", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.constructionCosts.setReadOnly(True)
        self.constructionCosts.setObjectName(_fromUtf8("constructionCosts"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.constructionCosts)
        self.label_10 = QtGui.QLabel(self.groupBox_2)
        self.label_10.setText(QtGui.QApplication.translate("ManitaeSummary", "Other Expenses", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_10)
        self.otherExpenses = QtGui.QLineEdit(self.groupBox_2)
        self.otherExpenses.setEnabled(True)
        self.otherExpenses.setText(QtGui.QApplication.translate("ManitaeSummary", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.otherExpenses.setReadOnly(True)
        self.otherExpenses.setObjectName(_fromUtf8("otherExpenses"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.otherExpenses)
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        self.label_8.setText(QtGui.QApplication.translate("ManitaeSummary", "Total Profit", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout.setWidget(8, QtGui.QFormLayout.LabelRole, self.label_8)
        self.totalProfit = QtGui.QLineEdit(self.groupBox_2)
        self.totalProfit.setEnabled(True)
        self.totalProfit.setText(QtGui.QApplication.translate("ManitaeSummary", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.totalProfit.setReadOnly(True)
        self.totalProfit.setObjectName(_fromUtf8("totalProfit"))
        self.formLayout.setWidget(8, QtGui.QFormLayout.FieldRole, self.totalProfit)
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setText(QtGui.QApplication.translate("ManitaeSummary", "Total Revenue", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_4)
        self.totalRevenue = QtGui.QLineEdit(self.groupBox_2)
        self.totalRevenue.setText(QtGui.QApplication.translate("ManitaeSummary", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.totalRevenue.setReadOnly(True)
        self.totalRevenue.setObjectName(_fromUtf8("totalRevenue"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.totalRevenue)
        self.label_12 = QtGui.QLabel(self.groupBox_2)
        self.label_12.setText(QtGui.QApplication.translate("ManitaeSummary", "Total Expenses", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_12)
        self.totalExpenses = QtGui.QLineEdit(self.groupBox_2)
        self.totalExpenses.setText(QtGui.QApplication.translate("ManitaeSummary", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.totalExpenses.setReadOnly(True)
        self.totalExpenses.setObjectName(_fromUtf8("totalExpenses"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.totalExpenses)
        self.gridLayout.addWidget(self.groupBox_2, 0, 1, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(ManitaeSummary)
        self.groupBox_3.setTitle(QtGui.QApplication.translate("ManitaeSummary", "Resources", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.resourceComboBox = QtGui.QComboBox(self.groupBox_3)
        self.resourceComboBox.setEditable(False)
        self.resourceComboBox.setObjectName(_fromUtf8("resourceComboBox"))
        self.gridLayout_5.addWidget(self.resourceComboBox, 0, 0, 1, 1)
        self.resourceLineEdit = QtGui.QLineEdit(self.groupBox_3)
        self.resourceLineEdit.setEnabled(True)
        self.resourceLineEdit.setReadOnly(True)
        self.resourceLineEdit.setObjectName(_fromUtf8("resourceLineEdit"))
        self.gridLayout_5.addWidget(self.resourceLineEdit, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox_3, 1, 0, 1, 1)
        self.groupBox_4 = QtGui.QGroupBox(ManitaeSummary)
        self.groupBox_4.setTitle(QtGui.QApplication.translate("ManitaeSummary", "Research", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.researchStatus = QtGui.QLabel(self.groupBox_4)
        self.researchStatus.setText(QtGui.QApplication.translate("ManitaeSummary", "Testing", None, QtGui.QApplication.UnicodeUTF8))
        self.researchStatus.setObjectName(_fromUtf8("researchStatus"))
        self.gridLayout_4.addWidget(self.researchStatus, 0, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 0, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem1, 0, 2, 1, 1)
        self.gridLayout.addWidget(self.groupBox_4, 1, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(ManitaeSummary)
        QtCore.QMetaObject.connectSlotsByName(ManitaeSummary)
        ManitaeSummary.setTabOrder(self.totalPopulation, self.workingPopulation)
        ManitaeSummary.setTabOrder(self.workingPopulation, self.taxedPopulation)
        ManitaeSummary.setTabOrder(self.taxedPopulation, self.totalMoney)
        ManitaeSummary.setTabOrder(self.totalMoney, self.taxRevenue)
        ManitaeSummary.setTabOrder(self.taxRevenue, self.otherRevenue)
        ManitaeSummary.setTabOrder(self.otherRevenue, self.totalRevenue)
        ManitaeSummary.setTabOrder(self.totalRevenue, self.workersSalary)
        ManitaeSummary.setTabOrder(self.workersSalary, self.constructionCosts)
        ManitaeSummary.setTabOrder(self.constructionCosts, self.otherExpenses)
        ManitaeSummary.setTabOrder(self.otherExpenses, self.totalExpenses)
        ManitaeSummary.setTabOrder(self.totalExpenses, self.totalProfit)
        ManitaeSummary.setTabOrder(self.totalProfit, self.resourceComboBox)
        ManitaeSummary.setTabOrder(self.resourceComboBox, self.resourceLineEdit)

    def retranslateUi(self, ManitaeSummary):
        pass

